sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '9'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: cGljgZZ8kzg99Xq8aDLy/eOBHjvb5TXXf9qzJJlcRef7iHyGkGcWzmOlUfIntxapnXqxXJlFrY3saw91OcJa8uZ/SEHJ7yqFp4agOZ71I8fHd2bRVJmL9rcGW+nU4RDhEZunUkwDlb0D7GLLDp8ak2+ZwUwmXQD5bCQ+0fibOmw=
  email:
    recipients:
      secure: n1Uin23uDKrlYF5AOtWJN7tiiTDtJVYbOqKJZ8VDgAVa5BvYLDybktyJDCEVgZDG2UlHndlpGK7GfQswBLAR0CJIFErJoUR0UmlsmZobh2mtsofpe1lrYgS0k/Hsnnik4Z5kcBhLfXKFXFNilCaiCw/pxARsszXNMu2gsf9PJCY=
